import { store, useStore } from '../lib/simStore';

export function HelpOverlay() {
  const st = useStore();
  if (!st.helpOpen) return null;
  return (
    <div className="modal-backdrop" onClick={() => store.set('helpOpen', false)}>
      <div className="modal help" onClick={(e) => e.stopPropagation()}>
        <div className="modal-header">
          <div className="panel-label">Community Lab — how to read it</div>
          <button className="ghost" onClick={() => store.set('helpOpen', false)}>close</button>
        </div>
        <div className="modal-body">
          <section className="modal-section">
            <h2>What you are looking at</h2>
            <p>An agent-based life-course microsimulation of <b>Unity Province</b>: three cities — rich, church-going <b>Emmaus</b>; secular <b>Newhaven</b>, with no church, mosque or temple; poor, devout <b>Ithemba</b> — around the shared <b>Unity Centre</b> (the central hospital, the CBD with Government House, the Reserve Bank, the provincial police and the mall, and Unity Park with its stadium and concert hall), with the <b>provincial airport</b> to the south-east. A hundred households at the start, every person an agent with a Big Five personality (drawn as a classical shape), sex (colour), age (size), education (ticks), health (ring) and a profession. People sleep, eat, work, school, shop, visit, worship (or not), court, marry, have children, fall ill, are treated at their city's clinic or referred to the central hospital, age and die — on published South African demographic bases. Intruders arrive from outside; the police, the pastor, the doctor and the neighbours respond.</p>
            <p><b>Getting about.</b> Households drive their cars (the estates run to one per driver); anyone else takes the <b>Hyperline</b> — the province's train, on the elevated guideway that calls at Emmaus, Unity Central, Ithemba, the Airport and Newhaven — or a <b>bus</b> on one of the four lines into the terminus, or hails a <b>minibus taxi</b>. Ambulances fetch the admitted from home and attend the worst accidents. Two aeroplanes fly five return trips a day from the airport; the executives, bankers and professionals fly out for the day and come home on the evening flight. The Hyperline is hypersonic in earnest — a hop between stations takes about a second of simulated time — so the drawn train glides from platform to platform with a streak along the guideway.</p>
            <p><b>E-hailing and what getting about costs.</b> Households that use the <b>Hamba</b> app order a car to their gate: the teal cars with a roof sign, green while the driver-partner is online and amber on a surge-priced trip. Driver-partners rent their cars by the week from Unity Fleet Rentals, which buys them on vehicle finance, so the repo rate reaches the rent. Every fare moves with the economy: the pump price follows oil and the rand; the taxi associations raise fares when diesel has climbed; Unity Transit reviews its fares each July; Hamba prices from the drivers&apos; costs (fuel, rent, the minimum wage) and from the state of demand (the output gap, incomes, unemployment), and surges when there are too few cars. The Reserve Bank&apos;s committee votes on the repo rate every second month, and Treasury cuts the fuel levy for a few months when the pump price spikes. See Analytics, Finance, Transport.</p>
            <p><b>Children.</b> No child under ten is left without someone of fourteen or more: when the household is out, a neighbour or grandparent who is free comes to mind them (the inspector shows "minding …"), or the child goes along — and in the animated day a small child leaving with a grown-up keeps their pace and shares their car, taxi or bus.</p>
            <p><b>Who is where.</b> A place with nobody in it is drawn slightly greyed: a house whose household has all gone out to work, school or church, a shop after hours, a church on a weekday, a parked car, an empty bus. Colour returns the moment someone is inside.</p>
          </section>
          <section className="modal-section">
            <h2>Time</h2>
            <p>The speed control runs from real time (1×) to thirty years per minute. Up to one hour per second the simulation is <b>animated</b>: people walk the roads, drive the family car, hold conversations. Faster than that it becomes a <b>time-lapse</b>: only the daily demographic, health and economic processes run and people are shown where their day plan puts them. Both modes run the same day-step pipeline, so outcomes do not depend on the speed you watch at.</p>
          </section>
          <section className="modal-section">
            <h2>Drilling in and out</h2>
            <p>Scroll to zoom, drag to pan. <b>Double-click a house</b> to drop into it (interiors appear), <b>double-click a person</b> to follow them. When two people are talking, zoom in on them to see the exchange live; with an AI provider set, the exchange is scripted by the model from their personalities, relationship, mood and recent events. The breadcrumb at the top-left steps back out: Province › City › Settlement › House › Person; the fly-to buttons on the right jump to a city, the airport, the CBD, Unity Park or the hospital.</p>
            <p><b>Zoom past the rooms and the map becomes 3D.</b> The plan fades into a scene seen from above, and the moment the scene has the picture the camera swings down to a low view along the street, the horizon in the top of the frame; coming closer only brings it nearer, down to eye level, until the people are a hand's breadth tall and, closer still, a face fills the screen: the houses roofless like a doll's house, the rooms furnished at their spots (look down into them with the right button, or orbit with <kbd>Alt</kbd> and the left). Everyone is a person of their own — their family's likeness, their age and build, their hair's colour from the pigment they inherited, dressed for the day (a uniform at work, school clothes, Sunday best at church, warmer in winter) — and moves in their own way: walking at their own pace and keeping to the left, shifting their weight while they wait, arms folded or hands in pockets, glancing about, checking a phone. People talking stand in a circle and look at whoever is speaking (their eyes converge on them), who talks with their hands (more so in a heated exchange, quieter in grief); listeners nod and laugh along. In cars, taxis and buses you can see who is aboard, in their seats with the driver at the wheel — from above the roofs fade away like the houses'. The sun and sky follow the clock and the season, the trees stir in the wind (jacarandas flower in spring), at night the lived-in rooms glow and the pupils widen. In bed, a duvet drapes over each sleeper the way a cloth settles over the body beneath it (their trunk and limbs as the collision capsules a cloth simulation would use), and what lies under it is not drawn, so no elbow or knee comes through. Names and speech float over the scene; a click still picks a person or a house, a double-click follows or drops in. The <b>3D</b> button beside the zoom keeps the flat map at every zoom instead.</p>
            <p><b>Getting about the scene: Unreal Engine's viewport controls.</b> Hold the <b>right button</b> and move the mouse to look about; drag with the <b>left button</b> to move forward and back along the ground and turn; the <b>middle button</b>, or <b>left and right together</b>, slides sideways and straight up and down. Hold <b>Alt</b> (or Ctrl, on desktops whose window manager takes Alt-drags) to orbit with the left button, dolly with the right, track across the view with the middle. The <b>wheel</b> dollies in and out toward the ground under the cursor, as on the map (coming in from the map, that is the swing down to the street; going out, the lift back to the plan); with a button held it sets the camera speed instead (×1.1 a notch). With a button held, <kbd>W</kbd> <kbd>A</kbd> <kbd>S</kbd> <kbd>D</kbd> fly where the camera looks, <kbd>E</kbd> / <kbd>Q</kbd> go up and down, <kbd>R</kbd> / <kbd>F</kbd> up and down the camera's own way, <kbd>C</kbd> / <kbd>Z</kbd> zoom the lens in and out (it springs back when you let go). Without a button the arrow keys, <kbd>Page Up</kbd> / <kbd>Page Down</kbd> and the numpad (8 2 4 6, 9 7, + −, 1 3) do the same; <kbd>Home</kbd> levels the view, north up. Flight has Unreal's weight (it accelerates and coasts to a stop), everything scales with the distance to what the camera looks at, and the speed, sensitivity and inversions are in the settings. On the flat map any button drags the map and the wheel zooms about the cursor, as in an orthographic viewport; W A S D and the arrows pan, + and − zoom.</p>
            <p><b>A game controller</b> works as soon as it is plugged in, as Unreal's editor joystick: the left stick moves, the right stick looks (stick up looks down, as Unreal has it; the settings flip it), the triggers go down and up, the bumpers widen and narrow the lens, the d-pad steps the move (up / down) and turn (left / right) multipliers; A picks whoever is at the centre, B backs out, X follows them, Y switches 3D on or off, Start plays or pauses, View shows the legend, a stick click levels the view.</p>
          </section>
          <section className="modal-section">
            <h2>Directing the scene</h2>
            <p>Click the <b>clock</b> in the header to open the scene controls. Jump straight to a moment worth watching (the Sunday service, fellowship afterwards, a school morning, market day, Bible study, the small hours), hop forward by an hour or a year, go to a date, or move to the start of a season. The time field is a clock you can pick from, type into or nudge by the hour, and the row of times beneath it sets one in a single click. Note that the browser draws its own date and time controls in whatever format its locale uses, which may be a 12-hour clock even though the app's own clock is 24-hour. Nothing is skipped: every day in between is still simulated, only the animation is. Time runs forward, so to go back you rewind, which rebuilds the community from the same seed.</p>
            <p>The same panel <b>forces the weather</b> — a storm, a heat wave, a cold snap — so you can see how the community responds without waiting for one. That is an intervention rather than an assumption, so it is written into the event ledger and the header shows a <i>forced</i> badge; hold it until you release it, or let it lapse at midnight. The season always follows the calendar, so it is never faked.</p>
          </section>
          <section className="modal-section">
            <h2>Panels</h2>
            <p>Both side panels start closed so the village has the whole window. The buttons just under the header, at the top corner of each panel, bring them back (<kbd>[</kbd> and <kbd>]</kbd>), and your choice is remembered.</p>
          </section>
          <section className="modal-section">
            <h2>Keys</h2>
            <p><kbd>Space</kbd> play / pause · <kbd>1</kbd>–<kbd>9</kbd>, <kbd>0</kbd> speed presets · <kbd>Esc</kbd> drill out / clear selection · <kbd>F</kbd> follow selected · <kbd>[</kbd> <kbd>]</kbd> toggle side panels · <kbd>L</kbd> legend · <kbd>?</kbd> this help</p>
          </section>
          <section className="modal-section">
            <h2>For actuaries</h2>
            <p>Every rate is an explicit input (left panel, <i>Scenario</i>) and the whole basis is hashed. The analytics strip at the bottom expands into actual-vs-expected mortality by age band and sex with Poisson intervals, realised fertility against the ASFR basis, an experience-adjusted life expectancy, a community funeral &amp; life scheme with its surplus process and ruin flag, and a Monte Carlo runner for replications. The <b>Actuarial</b> tile opens a workbench in the International Actuarial Notation, valued at a rate you pick from the province's own: the theory of interest (timelines, annuities-certain, a loan's yield), life contingencies on the table (commutation functions, A<sub>x</sub>, ä<sub>x</sub>, net premiums, reserves), the burial society priced by the equivalence principle, its classical risk theory (the adjustment coefficient, Lundberg, a simulated surplus fan, the SAM one-year 99.5% SCR), a cohort-component projection, a worker's retirement fund with the two pots, the old-age grant's liability, and the standards behind each figure. See <code>docs/ODD.md</code> and <code>docs/ASSUMPTIONS.md</code> in the repository.</p>
          </section>
        </div>
      </div>
    </div>
  );
}
