// The manual's reference pages, generated from the engine itself:
//
//   docs/reference/basis.md       every scenario parameter: its meaning (the doc comment it carries in
//                                 src/sim/params.ts, as the workbench's JSON schema reads it), its default, and
//                                 the range or choices a province file may set; the settlement tiers; the
//                                 mortality presets with the life expectancies they imply; the fertility shapes
//   docs/reference/indicators.md  the lab's indicators (METRICS, src/sim/experiment.ts)
//   docs/reference/templates.md   the lab's ready-made experiments (src/shared/templates.ts)
//   generated/sample/…            the sample workspace's files (src/shared/sample.ts), which the manual includes
//
// Run it from the repository root whenever the engine changes, and commit what it writes:
//
//   bun manual/scripts/reference.ts
//
// It fails if a parameter has neither a doc comment nor a note below, or belongs to no group, so a new parameter
// cannot slip into the engine without reaching the manual.

import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { MAX_EXPERIMENT_ARMS, MAX_EXPERIMENT_SEEDS, MAX_EXPERIMENT_YEARS, MAX_SEED_YEARS, MAX_SHOCKS, type Shock } from '../../src/shared/exchange';
import { APP_VERSION } from '../../src/shared/exports';
import { SAMPLE_FILES } from '../../src/shared/sample';
import { TEMPLATES } from '../../src/shared/templates';
import { METRICS } from '../../src/sim/experiment';
import { ASFR_SHAPE_LATE, ASFR_SHAPE_SA, tfrOf, type AsfrBand } from '../../src/sim/fertility';
import { MORTALITY_PRESETS, buildQxTable, lifeExpectancy, u5mr } from '../../src/sim/mortality';
import { DEFAULT_PARAMS, type ScenarioParams } from '../../src/sim/params';
import { CHOICES, NOT_PATCHABLE, PARAM_RANGES, TIER_SHARES } from '../../src/sim/patch';
import { CLIMATES } from '../../src/sim/weather';

const ROOT = join(import.meta.dir, '..', '..');
const MANUAL = join(ROOT, 'manual');
const STAMP = `<!-- Generated by manual/scripts/reference.ts from the engine (Community Lab ${APP_VERSION}). Do not edit by hand: change the engine and run \`bun manual/scripts/reference.ts\`. -->`;

// ── Doc comments, read exactly as src/client/workbench/schema.ts reads them ──

function docComments(src: string, iface: string): Record<string, string> {
  const start = src.indexOf(`export interface ${iface} {`);
  if (start < 0) return {};
  let depth = 0;
  let end = start;
  for (let i = src.indexOf('{', start); i < src.length; i++) {
    if (src[i] === '{') depth++;
    else if (src[i] === '}' && --depth === 0) {
      end = i;
      break;
    }
  }
  const body = src.slice(start, end);
  const out: Record<string, string> = {};
  const re = /\/\*\*([\s\S]*?)\*\/\s*\n\s*([A-Za-z0-9_]+)\??\s*:/g;
  for (let m = re.exec(body); m; m = re.exec(body)) {
    out[m[2]] = m[1]
      .split('\n')
      .map((l) => l.replace(/^\s*\*\s?/, '').trim())
      .filter(Boolean)
      .join(' ');
  }
  return out;
}

const PARAMS_SRC = readFileSync(join(ROOT, 'src/sim/params.ts'), 'utf8');
const DOCS = docComments(PARAMS_SRC, 'ScenarioParams');
const TIER_DOCS = docComments(PARAMS_SRC, 'CommunityProfile');

// What the doc comments leave unsaid. A note is added after the doc comment, or replaces it where the comment
// introduces a pair (TypeScript lets one comment stand over two fields) or says something the code does not do.
// Each note was read from the code it cites.
const EBENEZER = 'Ebenezer\'s households only: every other settlement takes its tier\'s value (see Settlement tiers below).';
const NOTES: Partial<Record<keyof ScenarioParams, string>> = {
  seed: 'The province\'s seed: the same seed and basis give the same households, the same weather and the same history, on any machine. In a province file it is `seed`, beside the basis; an experiment chooses its own seeds.',
  startDate: 'The first day of the run (YYYY-MM-DD).',
  households:
    'Households seeded in Ebenezer, the original village, at the start. Every other settlement seeds the count its layout gives it, so the default province starts with 100 households.',
  ageProfile:
    'The mix of household types at the start (families, couples, single parents, multigenerational, elderly, single): young, balanced or ageing. The low-income settlements always start young.',
  educationMix: EBENEZER,
  healthProfile:
    'The health setting: South African rural or urban, or a developed country. It sets the prevalence of chronic conditions at the start (HIV prevalence is a tenth higher in sa-rural); developed also lowers the infection rates, maternal mortality and the chance of finding work.',
  mortalityPreset: 'The mortality table the province lives on and A/E is measured against (see the presets below).',
  fertilityShape: 'The shape of the age-specific fertility schedule, scaled to the TFR (see the shapes below).',
  marriageAgeM: 'Mean age at first marriage, men; the courtship hazard peaks a year before it.',
  marriageAgeF: 'Mean age at first marriage, women; the courtship hazard peaks a year before it.',
  carOwnership: `Chance that a household with a driver has a car at the start, raised by 30% above R15,000 a month of income and cut by 40% below it. ${EBENEZER}`,
  churchAttendance:
    'Share of residents at the Sunday service in a typical week, and the mean of each person\'s faith, in the church-going cities (Emmaus and Ithemba; Newhaven has no church). Households decide together, so realised attendance tracks it closely.',
  climate: 'The climate normals the daily weather is drawn around (see the climates below).',
  funeralPremium: 'Monthly funeral premium per covered household (ZAR), indexed by CPI.',
  funeralBenefit: 'The funeral benefit the society pays on the death of a covered member (ZAR), indexed by CPI.',
  lifeCoverPremium: 'Monthly life premium per covered adult aged 18 to 64 (ZAR), indexed by CPI.',
  funeralCoverShare: `Share of households with funeral cover at the start. ${EBENEZER}`,
  lifeCoverShare: `Share of households with life cover at the start. ${EBENEZER}`,
  medicalAidShare: `Chance that a household is on a medical scheme at the start, raised by 60% above R25,000 a month of income and cut by 40% below it. ${EBENEZER}`,
  childGrant: 'Child support grant (ZAR a month) for children under 18 in households with income per person below 2.5 poverty lines; indexed by CPI.',
  oldAgeGrant: 'Older persons grant (ZAR a month) for residents of 60 and over without income, R20 more from 75; indexed by CPI.',
  repoRate: 'The Reserve Bank\'s repo rate at the start (6.75% in January 2026); the Monetary Policy Committee sets it from then on.',
  inflationStart: 'National CPI inflation at the start (4.3%).',
  inflationTarget: 'The Reserve Bank\'s inflation target, which the committee\'s Taylor rule aims at.',
  bankFoundingCapital: 'The Mutual Bank\'s founding share capital (ZAR); R10 million is the Mutual Banks Act\'s minimum.',
  bankMemberShare: 'Member shares each household subscribes in the Mutual Bank (ZAR).',
};
const REPLACE = new Set<keyof ScenarioParams>(['seed', 'households', 'churchAttendance', 'marriageAgeM', 'funeralPremium', 'funeralCoverShare', 'childGrant', 'repoRate', 'inflationStart', 'bankFoundingCapital', 'carOwnership', 'medicalAidShare']);

// ── Groups, so the reference reads by subject rather than by declaration order ──

const GROUPS: Array<{ title: string; keys: Array<keyof ScenarioParams> }> = [
  { title: 'The run', keys: ['seed', 'startDate', 'placeName', 'regionName', 'journalRetentionMonths'] },
  {
    title: 'Population and households',
    keys: ['households', 'meanHouseholdSize', 'ageProfile', 'maleShareAtBirth', 'educationMix', 'homeschoolShare', 'tertiaryProgression', 'youthEmigrationHazard', 'immigrationHazard', 'retirementAge'],
  },
  { title: 'Mortality', keys: ['mortalityPreset', 'mortalityImprovement', 'bereavementMultiplier', 'povertyMortalityMultiplier'] },
  { title: 'Health', keys: ['healthProfile', 'hivEnabled', 'careQuality', 'fluAttackRate'] },
  { title: 'Fertility, courtship and marriage', keys: ['fertilityShape', 'tfr', 'contraceptionShare', 'marriageAgeM', 'marriageAgeF', 'courtshipHazard', 'divorceHazard'] },
  { title: 'Society, safety and getting about', keys: ['churchAttendance', 'intrudersPerYear', 'disputeRate', 'policeEffectiveness', 'carOwnership', 'roadAccidentPer1000Km', 'trainMach', 'climate'] },
  { title: 'The burial society and cover', keys: ['funeralPremium', 'funeralBenefit', 'lifeCoverSum', 'lifeCoverPremium', 'funeralCoverShare', 'lifeCoverShare', 'medicalAidShare', 'schemeReserve'] },
  { title: 'Grants and poverty', keys: ['childGrant', 'oldAgeGrant', 'povertyLine'] },
  {
    title: 'The economy, tax and the bank',
    keys: ['repoRate', 'inflationStart', 'inflationTarget', 'minimumWageHourly', 'realWageGrowth', 'bracketIndexation', 'titheRate', 'churchS18A', 'bankFoundingCapital', 'bankMemberShare', 'councilStipend'],
  },
];
const SPECIAL = new Set(['tiers', 'mortalityOverride', 'shocks']); // tables of their own, or inputs with their own fields

// ── Checks: every parameter documented and grouped ──

const problems: string[] = [];
const grouped = new Set(GROUPS.flatMap((g) => g.keys as string[]));
for (const k of Object.keys(DEFAULT_PARAMS)) {
  if (SPECIAL.has(k)) continue;
  if (!grouped.has(k)) problems.push(`${k}: in no group (add it to GROUPS)`);
  if (!DOCS[k] && !NOTES[k as keyof ScenarioParams]) problems.push(`${k}: no doc comment in params.ts and no note here`);
}
for (const k of grouped) if (!(k in DEFAULT_PARAMS)) problems.push(`${k}: grouped but not a parameter any more`);
if (problems.length) {
  console.error(`reference: ${problems.length} problem(s)\n  ${problems.join('\n  ')}`);
  process.exit(1);
}

// ── Formatting ──

const esc = (s: string) => s.replace(/\|/g, '\\|');
const sentence = (s: string) => {
  const t = s.trim();
  return t && !/[.!?)]$/.test(t) ? `${t}.` : t;
};
const num = (x: number) => {
  if (Number.isInteger(x)) return Math.abs(x) >= 1_000 ? x.toLocaleString('en-GB') : String(x);
  return String(Number(x.toPrecision(6)));
};
const fmt = (v: unknown): string => {
  if (typeof v === 'number') return `\`${num(v)}\``;
  if (typeof v === 'boolean') return `\`${v}\``;
  if (typeof v === 'string') return `\`"${v}"\``;
  return `\`${JSON.stringify(v)}\``;
};

function describe(k: keyof ScenarioParams): string {
  const doc = DOCS[k] ? sentence(DOCS[k]) : '';
  const note = NOTES[k] ?? '';
  if (note && REPLACE.has(k)) return note;
  return [doc, note].filter(Boolean).join(' ');
}

function accepted(k: keyof ScenarioParams): string {
  if (NOT_PATCHABLE.has(k)) return k === 'seed' ? 'any text (a province file\'s `seed`)' : 'not settable from a file';
  const def = DEFAULT_PARAMS[k];
  if (k === 'educationMix') return 'six shares, normalised to sum to 1';
  if (typeof def === 'number') {
    const r = PARAM_RANGES[k];
    return r ? `${num(r[0])} to ${num(r[1])}` : 'any number';
  }
  if (typeof def === 'boolean') return '`true` or `false`';
  const c = CHOICES[k];
  if (c) return c.map((x) => `\`${x}\``).join(', ');
  if (k === 'startDate') return 'a date, `YYYY-MM-DD`';
  return 'a short text (60 characters at most)';
}

// ── basis.md ──

function basisPage(): string {
  const L: string[] = [];
  L.push(STAMP, '', '# Basis parameters', '');
  L.push(
    'Every assumption the engine makes is a parameter of the **basis**: the defaults below, changed in the *Scenario & basis* panel, in a province file\'s `basis`, or in an experiment\'s `base` and arms. The whole set is hashed into the **basis hash** printed on every export, so a result can always be traced to what it assumed.',
    '',
    'A province file only needs the parameters it changes. The editor completes each name and shows its meaning, range and default on hover, from the same source as this page. A value outside the range a file may set is left out, with a warning in **Problems**, and the rest of the file is applied.',
    '',
    `Where each default comes from is in [Assumptions and provenance](../model/assumptions.md).`,
    '',
  );
  for (const g of GROUPS) {
    L.push(`## ${g.title}`, '');
    L.push('| Parameter | Meaning | Default | A file may set |', '|---|---|---|---|');
    for (const k of g.keys) {
      let def = fmt(DEFAULT_PARAMS[k]);
      if (k === 'educationMix') def = Object.entries(DEFAULT_PARAMS.educationMix).map(([e, v]) => `${e} ${num(v)}`).join(', ');
      L.push(`| \`${k}\` | ${esc(describe(k))} | ${esc(def)} | ${esc(accepted(k))} |`);
    }
    L.push('');
    if (g.title === 'Mortality') L.push(...presetTables());
    if (g.title === 'Fertility, courtship and marriage') L.push(...asfrTable());
    if (g.title === 'Society, safety and getting about') L.push(...climateTable());
  }
  L.push(...tierTables());
  L.push('## Inputs with fields of their own', '');
  L.push(
    'Two inputs are not set through `basis`, because they are not single numbers:',
    '',
    `- **A mortality table** to live on instead of the preset: a province file\'s \`mortality\` (a CSV in the workspace, or a table inline), an experiment\'s \`baseMortality\` or an arm\'s \`mortality\`. See [Mortality tables](../workbench/mortality-tables.md).`,
    `- **Timed shocks**: \`shocks\` (at most ${MAX_SHOCKS}), each a \`mortality\`, \`repo\` or \`oil\` shock over a span of months. See [Province files](../workbench/province-files.md#shocks).`,
    '',
    'Both are hashed into the basis like any parameter when they are present, and absent otherwise, so a default province\'s basis hash does not depend on them.',
    '',
  );
  return L.join('\n');
}

function presetTables(): string[] {
  const L: string[] = [];
  L.push('### Mortality presets', '');
  L.push(
    'Each preset is a Heligman–Pollard law with its own parameters for men and women. The life expectancies, infant and under-five mortality are what each table implies before any improvement (a period life table on the preset, radix 100,000, a₀ = 0.1), computed by the engine\'s own functions.',
    '',
  );
  L.push('| `mortalityPreset` | Table | e₀ men / women | e₆₅ men / women | q₀ men / women (‰) | Under-five, men / women (‰) |', '|---|---|---|---|---|---|');
  for (const p of MORTALITY_PRESETS) {
    const t = buildQxTable(p);
    const e = (q: number[], x: number) => lifeExpectancy(q, x).toFixed(1);
    L.push(
      `| \`${p.id}\` | ${esc(p.label)} | ${e(t.M, 0)} / ${e(t.F, 0)} | ${e(t.M, 65)} / ${e(t.F, 65)} | ${(t.M[0] * 1000).toFixed(1)} / ${(t.F[0] * 1000).toFixed(1)} | ${u5mr(t.M).toFixed(1)} / ${u5mr(t.F).toFixed(1)} |`,
    );
  }
  L.push('');
  L.push('Their sources, and the parameters themselves:', '');
  L.push('| Preset | Source | Fitted to | Men: A, B, C, D, E, F, G, H | Women: A, B, C, D, E, F, G, H |', '|---|---|---|---|---|');
  for (const p of MORTALITY_PRESETS) {
    const hp = (h: typeof p.male) => [h.A, h.B, h.C, h.D, h.E, h.F, h.G, h.H].map((x) => num(x)).join(', ');
    L.push(`| \`${p.id}\` | ${esc(p.source)} | ${p.form === 'single' ? 'single-year q' : 'n-year interval q (1q0, 4q1, 5qx), converted to single years'} | ${hp(p.male)} | ${hp(p.female)} |`);
  }
  L.push('');
  return L;
}

function asfrTable(): string[] {
  const L: string[] = [];
  const shapes: Array<[string, AsfrBand[]]> = [
    ['sa', ASFR_SHAPE_SA],
    ['late', ASFR_SHAPE_LATE],
  ];
  L.push('### Fertility shapes', '');
  L.push(
    `Births per 1,000 women a year by age band, as the shapes are written. The engine scales the chosen shape so that its total fertility equals \`tfr\` (the default ${num(DEFAULT_PARAMS.tfr)}), then adjusts each woman\'s monthly chance for her partnership, parity, schooling and health.`,
    '',
  );
  L.push(`| Band | ${shapes.map(([id]) => `\`${id}\``).join(' | ')} |`, `|---|${shapes.map(() => '---|').join('')}`);
  for (let i = 0; i < ASFR_SHAPE_SA.length; i++) L.push(`| ${ASFR_SHAPE_SA[i].band} | ${shapes.map(([, s]) => num(Math.round(s[i].rate * 1000 * 10) / 10)).join(' | ')} |`);
  L.push(`| TFR as written | ${shapes.map(([, s]) => tfrOf(s).toFixed(2)).join(' | ')} |`, '');
  return L;
}

function climateTable(): string[] {
  const L: string[] = ['### Climates', ''];
  L.push('| `climate` | Normals |', '|---|---|');
  for (const c of CLIMATES) L.push(`| \`${c.id}\` | ${esc(c.label)} |`);
  L.push('');
  return L;
}

function tierTables(): string[] {
  const L: string[] = [];
  const tiers = DEFAULT_PARAMS.tiers;
  const ids = Object.keys(tiers) as Array<keyof typeof tiers>;
  L.push('## Settlement tiers', '');
  L.push(
    'Each settlement belongs to a wealth tier, and its households start from the tier\'s profile: schooling, cars, cover, savings and work. Ebenezer\'s own households read the baseline parameters above instead (`educationMix`, `carOwnership` and the cover shares, whose defaults are the `middle` profile\'s values), and open with 0.5 to 6 months of income in savings, although its tier is `affluent`. How many households each settlement starts with is part of its layout, not its tier. A file may set the shares marked *settable*, tier by tier, under `basis.tiers`:',
    '',
    '```json',
    '"basis": { "tiers": { "low-income": { "funeralCoverShare": 1 } } }',
    '```',
    '',
  );
  const fields: Array<[string, (p: (typeof tiers)[keyof typeof tiers]) => string]> = [
    ['carOwnership', (p) => num(p.carOwnership)],
    ['secondCarShare', (p) => num(p.secondCarShare)],
    ['funeralCoverShare', (p) => num(p.funeralCoverShare)],
    ['lifeCoverShare', (p) => num(p.lifeCoverShare)],
    ['medicalAidShare', (p) => num(p.medicalAidShare)],
    ['unemployment', (p) => num(p.unemployment)],
    ['savingsMonths', (p) => `${num(p.savingsMonths[0])} to ${num(p.savingsMonths[1])}`],
  ];
  L.push(`| Field | Meaning | ${ids.map((t) => `\`${t}\``).join(' | ')} |`, `|---|---|${ids.map(() => '---|').join('')}`);
  for (const [f, get] of fields) {
    const TIER_NOTES: Record<string, string> = {
      carOwnership: 'Chance that a household with a driver has a car at the start, scaled by income as `carOwnership` above.',
      funeralCoverShare: 'Share of households with funeral cover at the start.',
      lifeCoverShare: 'Share of households with life cover at the start.',
      medicalAidShare: 'Chance of a medical scheme at the start, scaled by income as `medicalAidShare` above.',
    };
    const doc = TIER_NOTES[f] ?? (TIER_DOCS[f] ? sentence(TIER_DOCS[f]) : '');
    const settable = TIER_SHARES.has(f) ? ' *Settable.*' : '';
    L.push(`| \`${f}\` | ${esc(doc)}${settable} | ${ids.map((t) => get(tiers[t])).join(' | ')} |`);
  }
  L.push('');
  L.push('Schooling at the start, by tier (shares of adults):', '');
  const edu = Object.keys(DEFAULT_PARAMS.educationMix);
  L.push(`| Tier | ${edu.join(' | ')} |`, `|---|${edu.map(() => '---|').join('')}`);
  for (const t of ids) L.push(`| \`${t}\` | ${edu.map((e) => num((tiers[t].educationMix as unknown as Record<string, number>)[e])).join(' | ')} |`);
  L.push('');
  return L;
}

// ── indicators.md ──

const GROUP_TITLES: Record<string, string> = { demography: 'Demography', health: 'Health', insurance: 'Insurance', equity: 'Equity', economy: 'Economy', fiscal: 'The fiscus', justice: 'Safety' };
const BETTER: Record<string, string> = { higher: 'higher', lower: 'lower', neutral: 'neither' };

function indicatorsPage(): string {
  const L: string[] = [STAMP, '', '# Indicators', ''];
  L.push(
    `The ${METRICS.length} indicators every experiment, Monte Carlo run and script reports, as the engine defines them (\`METRICS\` in the script API). Each is computed from the run itself at its end; "per year" figures divide by the years the run lived.`,
    '',
    'An experiment reports each one per arm, over its seeds, and as a **paired effect** against the baseline with a 95% interval. *Better* is the direction counted as an improvement in "better in k of n seeds"; an indicator marked *neither* is reported without a direction.',
    '',
    'An indicator a run cannot estimate is reported as missing (—), and the seeds where it is missing are left out of its effect: life expectancy, for instance, needs at least three deaths of each sex.',
    '',
  );
  const groups = [...new Set(METRICS.map((m) => m.group))];
  for (const g of groups) {
    L.push(`## ${GROUP_TITLES[g] ?? g}`, '');
    L.push('| Id | Indicator | Unit | Better | Definition |', '|---|---|---|---|---|');
    for (const m of METRICS.filter((x) => x.group === g)) L.push(`| \`${m.id}\` | ${esc(m.label)} | ${esc(m.unit)} | ${BETTER[m.better]} | ${esc(sentence(m.description))} |`);
    L.push('');
  }
  return L.join('\n');
}

// ── templates.md ──

const AUDIENCE: Record<string, string> = { actuarial: 'For actuaries', government: 'For governments', social: 'For social developers' };
const LABEL = new Map(METRICS.map((m) => [m.id, m.label]));

function shockText(s: Shock): string {
  const span = `from month ${s.fromMonth} for ${s.months} month${s.months === 1 ? '' : 's'}`;
  if (s.kind === 'mortality') {
    const ages = s.minAge !== undefined || s.maxAge !== undefined ? ` at ages ${s.minAge ?? 0} to ${s.maxAge ?? 110}` : ' at every age';
    return `mortality ×${num(s.factor ?? 1)}${ages}, ${span}`;
  }
  if (s.kind === 'repo') return `repo ${(s.bp ?? 0) >= 0 ? '+' : ''}${s.bp} bp, ${span}`;
  return `Brent ×${num(s.factor ?? 1)}, ${span}`;
}

function templatesPage(): string {
  const YEARS = 10;
  const L: string[] = [STAMP, '', '# Lab templates', ''];
  L.push(
    `The ready-made experiments the [policy and stress lab](../analytics/lab.md) offers, and that \`template(id, years)\` returns in a script. Each changes one lever (or applies one stress), so an effect has one cause. Every number in them is a stated assumption you can change before running. The arms are shown here as built for a ${YEARS}-year run; a stress that lasts "the whole run" scales with the years you choose.`,
    '',
    `Limits for any experiment: at most ${MAX_EXPERIMENT_ARMS} arms, ${MAX_EXPERIMENT_SEEDS} seeds and ${MAX_EXPERIMENT_YEARS} years, and ${MAX_SEED_YEARS} province-years in all (seeds × years × runs per seed, the baseline included).`,
    '',
  );
  for (const aud of ['actuarial', 'government', 'social']) {
    L.push(`## ${AUDIENCE[aud]}`, '');
    for (const t of TEMPLATES.filter((x) => x.audience === aud)) {
      const spec = t.build(YEARS);
      L.push(`### ${t.title}`, '');
      L.push(`\`${t.id}\` · *${esc(t.question)}*`, '');
      L.push('| Arm | Changes |', '|---|---|');
      for (const a of spec.arms) {
        const changes: string[] = [];
        for (const [k, v] of Object.entries(a.params ?? {})) {
          if (k === 'tiers') changes.push(`and the same in every settlement tier (\`tiers\`)`);
          else changes.push(`\`${k}\`: ${fmt(v)} (default ${fmt((DEFAULT_PARAMS as unknown as Record<string, unknown>)[k])})`);
        }
        for (const s of a.shocks ?? []) changes.push(`${s.label}: ${shockText(s)}`);
        if (a.mortality) changes.push(`lives on the table "${a.mortality.label}"`);
        L.push(`| ${esc(a.label)} (\`${a.id}\`) | ${esc(changes.join('; '))} |`);
      }
      L.push('', `Leads with: ${t.focus.map((f) => LABEL.get(f) ?? f).join(', ')}.`, '');
    }
  }
  return L.join('\n');
}

// ── Write ──

function write(rel: string, text: string) {
  const path = join(MANUAL, rel);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, text.endsWith('\n') ? text : `${text}\n`);
  console.log(`reference: wrote manual/${rel}`);
}

write('docs/reference/basis.md', basisPage());
write('docs/reference/indicators.md', indicatorsPage());
write('docs/reference/templates.md', templatesPage());
rmSync(join(MANUAL, 'generated'), { recursive: true, force: true });
for (const f of SAMPLE_FILES) write(join('generated/sample', f.path), f.text);
