// Focused visual checks for the crowded-room, analytics and fullscreen states.
import puppeteer from 'puppeteer-core';
import { mkdirSync } from 'node:fs';
mkdirSync('data/shots', { recursive: true });
const browser = await puppeteer.launch({ executablePath: '/usr/bin/google-chrome', headless: true, args: ['--no-sandbox', '--disable-gpu', '--window-size=1900,1000'] });
const page = await browser.newPage();
await page.evaluateOnNewDocument(() => { try { localStorage.setItem('ia.theme', 'light'); } catch {} });
await page.setViewport({ width: 1900, height: 1000, deviceScaleFactor: 1 });
const errors: string[] = [];
page.on('pageerror', (e) => errors.push(String((e as Error).message)));
page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()); });
const run = (code: string) => page.evaluate(`(() => { ${code} })()`);
const shot = async (name: string, ms = 900) => { await new Promise((r) => setTimeout(r, ms)); await page.screenshot({ path: `data/shots/${name}.png` }); console.log('shot', name); };
await page.goto('http://localhost:5175/', { waitUntil: 'networkidle0', timeout: 60000 });
await page.waitForSelector('canvas');
// Evening at home: families in living rooms, conversations
await run(`const s=window.communityLab.store; s.setSpeed('x60'); s.sim.advance(19*60+20); s.play();`);
await new Promise((r) => setTimeout(r, 2500));
const big = await run(`const s=window.communityLab.store; const w=s.sim.world; const hh=Object.values(w.households).filter(h=>!h.dissolvedDay).sort((a,b)=>b.memberIds.length-a.memberIds.length)[0]; s.select({kind:'household', id:hh.id},{focus:true}); s.camera.tzoom = 12; return hh.name;`);
console.log('household', big);
await shot('20-crowded-room', 2500);
await run(`const s=window.communityLab.store; s.pause(); s.resetCamera(); s.select({kind:'household', id: Object.values(s.sim.world.households)[3].id}); s.bump();`);
await shot('21-household-highlight', 1200);
await run(`const s=window.communityLab.store; s.select(null); s.sim.runDays(800); s.bump(); s.openDrawer('economy');`);
await shot('22-economy', 1500);
await run(`window.communityLab.store.openDrawer('mortality')`);
await shot('23-mortality', 1500);
await run(`window.communityLab.store.setDrawerFull(true)`);
await shot('24-mortality-full', 1500);
await run(`window.communityLab.store.openDrawer('population')`);
await shot('25-population-full', 1500);
await run(`window.communityLab.store.openDrawer('health')`);
await shot('26-health-full', 1500);
console.log('errors', errors.length, errors.slice(0, 5));
await browser.close();
